highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://yashpalahlawat.github.io/vitae/
author: Yashpal


baseurl: /vitae/
title: Yashpal's Resume
name: Yashpal
email: ahlawatyashpal8@gmail
email_full: mailto:ahlawatyashpal8@gmail.com
#website: github.io/YashpalAhlawat
#website_full: https://yaspalahlawat.github/
github: trending
twitter: twitter
tel: +91 9466428221
tel_full: tel:+91 9466428221
google_maps: 'https://www.google.co.in/maps/place/Sector+7,+Faridabad,+Haryana+121006/@27.9500826,77.2843845,9z/data=!4m5!3m4!1s0x390cdc793adfce0f:0xd83c2b33251b0821!8m2!3d28.3623771!4d77.3252633'
address: house no 1089 sec 7C
postcode: 121 006 
city: Faridabad
country: India
google_analytics: UA-88906378-1

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-merlot