highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: https://yashpalahlawat.github.io/vitae/
author: FÃ¡bio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Yashpal's Resume
name: Yashpal
email: ahlawatyashpal8@gmail.com
email_full: mailto:ahlawatyashpal8@gmail.com
#website: github.io/YashpalAhlawat
#website_full: https://biomadeira.github.io/sustain
github: trending
twitter: twitter
tel: +91 9466428221
tel_full: tel:+91 9466428221
google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: house no 1089 sec 7C
postcode: 121 006 
city: Faridabad
country: India
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
